<template>
  <div class="content patient-list-page">
    <div class="animated fadeIn">
      <TopNavBar heading="Patients"></TopNavBar>

      <div class="row">
        <div class="col-lg-12">
          <div class="patient-content">
            <div class="title">Patient List</div>

          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-12">
          <div class="patient-search">
             <div class="search">
              <div class="input-group md-form form-sm form-1 pl-0">
                <div class="input-group-prepend">
                  <span class="input-group-text lighten-3" id="basic-text1">
                    <i class="fas fa-search" aria-hidden="true"></i>
                  </span>
                </div>
                <input
                  class="form-control my-0 py-1 border-left-0"
                  type="text"
                  placeholder="Patient Name, ID, NID"
                  aria-label="Search"
                  v-model="search"
                />
              </div>
            </div> 

          </div>
        </div>
      </div>
      <div class="row mt-0">
        <div class="col-lg-12">
          <div class="patient-list">
            <div class="table-responsive">
              <table class="table" v-if="patients.length > 0">
                <thead>
                  <tr>
                    <th scope="col">Name</th>
                    <th scope="col">NID</th>
                    <th scope="col">Age</th>
                    <th scope="col">Gender</th>
                    <th scope="col">Last Generated</th>
                    <th scope="col">Generated By</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                  <tr
                    class="pointer bg-white tr-border-bttom-grey"
                    v-for="(patient, index) in filteredList"
                    :key="index"
                  >
                    <template>
                      <td>
                        {{
                          patient.body.first_name + " " + patient.body.last_name
                        }}
                      </td>

                      <!-- <td>P2342343</td> -->
                      <td>{{ patient.body.nid }}</td>
                      <td>{{ patient.body.age }}</td>
                      <td>{{ patient.body.gender.toUpperCase()
                        }}</td>
                      <td>
                        {{ patient.body.prescription ? moment(patient.body.prescription.generated_at).format('DD-MM-YYYY') : ''}}
                      </td>
                      <td>
                        {{ patient.body.prescription ? getGeneratedby(patient.body.prescription.generated_by) : ''}}
                      </td>
                      <td>
                        <a :href="patient.body.prescription.url" target="blank" class="btn btn-primary btn-sm">View</a>
                        <!-- {{ patient.body.prescription ? getGeneratedby(patient.body.prescription.generated_by) : ''}} -->
                      </td>
                    </template>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
// @ is an alias to /src
import Vue from "vue";
import moment from "moment";
import { VuejsDatatableFactory } from "vuejs-datatable";
import TopNavBar from '../TopNavBar.vue';
Vue.use(VuejsDatatableFactory);

export default {
  name: "patients",
  components: {TopNavBar},
  data() {
    return {
      patients: [],
      search: "",
      users: []
    };
  },
  computed: {
    filteredList() {
      return this.patients.filter((patient) => {
        return (
          patient.body.first_name
            .toLowerCase()
            .includes(this.search.toLowerCase()) ||
          patient.body.last_name
            .toLowerCase()
            .includes(this.search.toLowerCase()) ||
          patient.body.nid.toString().includes(this.search.toLowerCase())
        );
      });
    },
  },
  methods: {

    getGeneratedby(id) {
      let matchedUser = this.users.find(usr => usr.uid == id);
      return matchedUser ? matchedUser.name : '';
    },
      getUsers() {
      let loader = this.$loading.show();
      this.$http.get("/users").then(
        response => {
          loader.hide();
          if (response.status == 200) {
            this.users = response.data;
          }
        },
        error => {
          loader.hide();
        }
      );
    },
    getPatients() {
      let loader = this.$loading.show();
      this.$http.get("/patients/prescriptions").then(
        (response) => {
          if (response.status == 200) {
            this.patients = response.data.data;
            console.log('prestcibed patients: ', this.patients)
            loader.hide();
          }
        },
        (error) => {
          loader.hide();
        }
      );
    },

    getId(identifier, type) {
      if (!identifier) {
        return "";
      }
      let id = identifier.find((x) => x.use === type);

      if (id) {
        return id.value;
      }
      return "";
    },
  },
  mounted() {
    this.getPatients();
    this.getUsers();
  },
};
</script>

<style lang="">
</style>
