<template>
  <div class="content patient-list-page">
    <div class="animated fadeIn">
      <TopNavBar heading="Patients"></TopNavBar>

      <div class="row">
        <div class="col-lg-12">
          <div class="patient-content">
            <div class="title">Patient List</div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-12">
          <div class="patient-search">
             <div class="search">
              <div class="input-group md-form form-sm form-1 pl-0">
                <input
                  class="form-control my-0 py-1 border-right-0"
                  type="text"
                  placeholder="Patient Name, ID, NID"
                  aria-label="Search"
                  v-model="search"
                />
                 <div class="input-group-prepend">
                  <a href="javascript:void(0)" @click="getPatients('', 'last_item')" class="input-group-text lighten-3 text-decoration-none" id="basic-text1">
                    <i class="fas fa-search" aria-hidden="true"></i>
                  </a>
                </div>
              </div>
            </div> 

          </div>
        </div>
      </div>
      <div class="row mt-0">
        <div class="col-lg-12">
          <div class="patient-list" v-if="patients.length > 0">
            <div class="table-responsive">
              <table class="table" >
                <thead>
                  <tr>
                    <th scope="col">Name</th>
                    <th scope="col">NID</th>
                    <th scope="col">Age</th>
                    <th scope="col">Gender</th>
                    <th scope="col">Last Generated</th>
                    <th scope="col">Generated By</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                  <tr
                    class="pointer bg-white tr-border-bttom-grey"
                    v-for="(patient, index) in patients"
                    :key="index"
                  >
                    <template>
                      <td>
                        {{
                          patient.body.first_name + " " + patient.body.last_name
                        }}
                      </td>
                      <td>{{ patient.body.nid }}</td>
                      <td>{{ patient.body.age }}</td>
                      <td>{{ patient.body.gender.toUpperCase()
                        }}</td>
                      <td>
                        {{ patient.body.prescription ? moment(patient.body.prescription.generated_at).format('DD-MM-YYYY') : ''}}
                      </td>
                      <td>
                        {{ patient.body.prescription ? getGeneratedby(patient.body.prescription.generated_by) : ''}}
                      </td>
                      <td>
                        <a :href="patient.body.prescription.url" target="blank" class="btn btn-primary btn-sm">View</a>
                        <!-- {{ patient.body.prescription ? getGeneratedby(patient.body.prescription.generated_by) : ''}} -->
                      </td>
                    </template>
                  </tr>
                </tbody>
              </table>
            </div>

            <nav aria-label="Page navigation">
              <ul class="pagination my-3">
                <li class="page-item">
                  <button type="button" class="page-link"  @click="nextPrevPage('prev')" :disabled="disablePrevButton"> Previous </button>
                </li>
                <li class="page-item">
                  <button type="button" @click="nextPrevPage('next')"  class="page-link" :disabled="disableNextButton"> Next </button>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
// @ is an alias to /src
import Vue from "vue";
import moment from "moment";
import { VuejsDatatableFactory } from "vuejs-datatable";
import TopNavBar from '../TopNavBar.vue';
Vue.use(VuejsDatatableFactory);

export default {
  name: "patients",
  components: {TopNavBar},
  data() {
    return {
      patients: [],
      search: "",
      users: [],
      paginationOptions: {
        currentPage: 1,
        perPage: 20
      },
      lastItemId: '',
      disablePrevButton: false,
      disableNextButton: false,
    };
  },
  computed: {
    filteredList() {
      return this.patients.filter((patient) => {
        return (
          patient.body.first_name
            .toLowerCase()
            .includes(this.search.toLowerCase()) ||
          patient.body.last_name
            .toLowerCase()
            .includes(this.search.toLowerCase()) ||
          patient.body.nid.toString().includes(this.search.toLowerCase())
        );
      });
    },
  },
  methods: {
    scrollToTop() {
      window.scrollTo(0,0);
    },
    getGeneratedby(id) {
      let matchedUser = this.users.find(usr => usr.uid == id);
      return matchedUser ? matchedUser.name : '';
    },
      getUsers() {
      let loader = this.$loading.show();
      this.$http.get("/users").then(
        response => {
          loader.hide();
          if (response.status == 200) {
            this.users = response.data;
          }
        },
        error => {
          loader.hide();
        }
      );
    },
    getPatients(lastItemId = '', queryItemkey = 'last_item') {
      let loader = this.$loading.show();
        let searchKey = '';
        this.disablePrevButton = false;
        this.disableNextButton = false;
        if(this.search) {
          if(isNaN(this.search)) {
            searchKey = '&name=' + this.search;
          } else {
            searchKey = '&nid=' + this.search;
        }
      }

      this.$http.get("/patients/prescriptions?per_page=" + this.paginationOptions.perPage + '&' + queryItemkey + '=' + lastItemId  + searchKey).then(
        (response) => {
          console.log(response);
          if (response.status == 200) {
              loader.hide();
              if (response.data.error == true) {
              // let msg = queryItemkey == 'last_item' ? 'Reached Last Record' : 'Reached First Record';
              let msg = 'No record found';
              if ( queryItemkey == 'last_item') {
                this.disableNextButton = true;
              } 

              if ( queryItemkey == 'first_item') {
                this.disablePrevButton = true;
              }
              this.search = '';
              this.$toast.open({ message: msg, type: 'error'});
              // this.patients = [];
              return;
            }

            this.patients = response.data.data;
            
          }
        },
        (error) => {
          loader.hide();
        }
      );
    },
    nextPrevPage(type) {
      let dataLength = this.patients.length;

      if (type == 'next') {
        let lastItemId = '';
        if ( dataLength > 0) {
          lastItemId = this.patients[dataLength - 1].id;
        }
        this.getPatients(lastItemId, 'last_item');
      }

      if (type == 'prev') {
         let firstItemId = dataLength > 0 ? this.patients[0].id : '';
        this.getPatients(firstItemId, 'first_item');
      }
    },
    getId(identifier, type) {
      if (!identifier) {
        return "";
      }
      let id = identifier.find((x) => x.use === type);

      if (id) {
        return id.value;
      }
      return "";
    },
    setPages() {
      let numberOfPages = Math.ceil(this.paginationOptions.totalItems / this.paginationOptions.perPage);
			for (let index = 1; index <= numberOfPages; index ++) {
				this.paginationOptions.pages.push(index);
			}
    },
  },
  watch: {
  	'paginationOptions.currentPage': function(newVal, oldVal) {
      this.getPatients();
    }
  },
  mounted() {
    this.getPatients();
    this.getUsers();
    this.scrollToTop();
  },
};
</script>

<style lang="">
</style>
